# Generated by Django 4.1 on 2023-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_is_email_verified_user_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.CharField(default='000000', max_length=12),
        ),
    ]
