# Generated by Django 4.1 on 2023-05-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
