# Generated by Django 4.1 on 2023-05-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_topic_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.CharField(max_length=532),
        ),
    ]
