name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt


      - name: Deploy to PythonAnywhere
        uses: PythonAnywhere/pythonanywhere-ssh-deploy@master
        with:
          ssh-private-key: f31cac94cdec44cc414f8d4050013fc3b102e148
          remote-user: ocman
          remote-host: ssh.pythonanywhere.com
          remote-port: 22
          remote-path: /home/ocman/codebook-final4/
          args: migrate
