name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug output
        run: |
          echo "PA_PASSWORD: ********************"
          echo "Current directory: $(pwd)"
          echo "Contents of current directory: $(ls -la)"


      - name: Deploy to PythonAnywhere
        uses: appleboy/ssh-action@master
        with:
          username: ocman
          run: |
            echo "PA_PASSWORD: ********************22222222"
          password: $Q!Kk$nC@K_)#6R
          runn: |
            echo "PA_PASSWORD: 33333333333333333333333333"
          host: ssh.pythonanywhere.com
          port: 22
          script: |
            cd /home/ocman/codebook-final4
            git pull origin master
            pip install -r requirements.txt
            python manage.py migrate
