name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to PythonAnywhere
        uses: appleboy/ssh-action@master
        with:
          username: ocman
          key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACCAoRoHA+njH3b6on2vxGTnwnVylmuMwxmBGwgNukENJAAAAKCdfmSMnX5kjAAAAAtzc2gtZWQyNTUxOQAAACCAoRoHA+njH3b6on2vxGTnwnVylmuMwxmBGwgNukENJAAAAEA53Ptkt7K4emh1xTgQbN6BU55kRlQfkTuzSZfUejx7wYChGgcD6eMfdvqifa/EZOfCdXKWa4zDGYEbCA26QQ0kAAAAGnVzbWFubmF6aXJiYXJlZXRAZ21haWwuY29tAQID
          host: ssh.pythonanywhere.com
          port: 22
          script: |
            cd /home/ocman/codebook-final4
            git pull origin master
            pip install -r requirements.txt
            python manage.py migrate
