name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Archive code
      run: tar -czvf code.tar.gz .
    - name: Copy code to remote server
      uses: appleboy/scp-action@master
      with:
        source: ./codebook-final4.tar.gz
        target: ocman@ssh.pythonanywhere.com:/home/ocman/codebook-final4/
        ssh_key: f31cac94cdec44cc414f8d4050013fc3b102e148
    - name: SSH into remote server and deploy code
      uses: appleboy/ssh-action@master
      with:
        host: ssh.pythonanywhere.com
        username: ocman
        key: $Q!Kk$nC@K_)#6R
        script: |
          cd ~/codebook-final4
          tar -xzvf codebook-final4.tar.gz
          source /home/ocman/.virtualenvs/env/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          touch /var/www/ocman..pythonanywhere.com_wsgi.py

