name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Deploy to PythonAnywhere
      #   uses: PythonAnywhere/pythonanywhere-ssh-deploy@master
      #   with:
      #     ssh-private-key: ${{ secrets.PA_SSH_PRIVATE_KEY }}
      #     remote-user: ${{ secrets.PA_REMOTE_USER }}
      #     remote-host: ${{ secrets.PA_REMOTE_HOST }}
      #     remote-port: ${{ secrets.PA_REMOTE_PORT }}
      #     remote-path: ${{ secrets.PA_REMOTE_PATH }}
      #     args: migrate
