name: Deploy to PythonAnywhere
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Deploy to PythonAnywhere
        env:
          PA_SERVER: ocman.pythonanywhere.com
          PA_USER: ocman
          PA_WEBAPP: ocman
          PA_PASSWORD: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
        run: |
          echo "machine $PA_SERVER login $PA_USER password $PA_PASSWORD" > ~/.netrc
          git push "https://$PA_USER@$PA_SERVER/$PA_USER/$PA_WEBAPP.git" HEAD:main
