name: PythonAnywhere CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
    - name: Deploy to PythonAnywhere
      uses: appleboy/scp-action@master
      with:
        args: |
          -v
          -r
          -p
          --delete
          --exclude .git
          --exclude .github
          --exclude .venv
          . ocman@ssh.pythonanywhere.com:/home/ocman/codebook-final4/
      env:
        SSH_PASS: ${{ secrets.PYTHONANYWHERE_PASSWORD }}



# name: PythonAnywhere CI/CD

# on:
#   push:
#     branches: [ master ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.9
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.9'
#     - name: Install dependencies
#       run: |
#         python -m venv .venv
#         source .venv/bin/activate
#         pip install -r requirements.txt
#     - name: Deploy to PythonAnywhere
#       uses: appleboy/scp-action@master
#       with:
#         args: |
#           -v
#           -c "import shutil; shutil.copytree('.', '/home/ocman/ocman.pythonanywhere.com/codebook-final4', dirs_exist_ok=True)"
#         source: .
#         destination: "gc://ocman.pythonanywhere.com/codebook-final4"


