name: PythonAnywhere CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
    - name: Deploy to PythonAnywhere
      uses: appleboy/scp-action@v2
      with:
        source: .
        target: ocman@ssh.pythonanywhere.com:/home/ocman/codebook-final4/
        args: |
          -r
          -v
      env:
        SSH_PASS: "$Q!Kk$nC@K_)#6R"
    - name: Restart PythonAnywhere web app
      uses: sevity/ssh-action@v1.5.0
      with:
        command: "touch /var/www/ocman_pythonanywhere_com_wsgi.py"
        host: "ssh.pythonanywhere.com"
        username: "ocman"
        password: "$Q!Kk$nC@K_)#6R"
